import React, { Fragment} from 'react';
import ParallaxScrollView from 'react-native-parallax-scroll-view';
import {
  Text,
  View,
  TouchableOpacity,
  Animated,
} from 'react-native';

const ProductDetailScroll = () => {
  const scrollRef = React.createRef();

  return (
    <Fragment>
      <ParallaxScrollView
        ref={scrollRef}
        backgroundColor="blue"
        contentBackgroundColor="pink"
        parallaxHeaderHeight={300}
        renderScrollComponent={() => <Animated.ScrollView />}
        renderForeground={() => (
          <View
            style={{
              height: 300,
              flex: 1,
              alignItems: 'center',
              justifyContent: 'center',
            }}>
            <Text>Hello World!</Text>
          </View>
        )}>
        <View style={{height: 300}}>
          <View>
            <Text>
              Your project contains lock files generated by tools other than
              Yarn. It is advised not to mix package managers in order to avoi d
              resolution inconsistencies caused by unsynchronized lock files. To
              clear this warning, remove pack Your project contains lock files
              generated by tools other than Yarn. It is advised not to mix
              package managers in order to avoi d resolution inconsistencies
              caused by unsynchronized lock files. To clear this warning, remove
              pack Your project contains lock files generated by tools other
              than Yarn. It is advised not to mix package managers in order to
              avoi d resolution inconsistencies caused by unsynchronized lock
              files. To clear this warning, remove pack Your project contains
              lock files generated by tools other than Yarn. It is advised not
              to mix package managers in order to avoi d resolution
              inconsistencies caused by unsynchronized lock files. To clear this
              warning, remove pack Your project contains lock files generated by
              tools other than Yarn. It is advised not to mix package managers
              in order to avoi d resolution inconsistencies caused by
              unsynchronized lock files. To clear this warning, remove pack Your
              project contains lock files generated by tools other than Yarn. It
              is advised not to mix package managers in order to avoi d
              resolution inconsistencies caused by unsynchronized lock files. To
              clear this warning, remove pack
            </Text>
          </View>
        </View>
      </ParallaxScrollView>
      <TouchableOpacity
        onPress={() => {
          console.log('scroll ref ', scrollRef.current.scrollTo({x: 0, y: 0, animated: true}));
        }}>
        <Text> scroll top </Text>
      </TouchableOpacity>
    </Fragment>
  );
};
export default ProductDetailScroll;
