import React, {useRef, Fragment} from 'react';
import ParallaxScrollView from 'react-native-parallax-scroll-view';
import {SafeAreaView, Text, View, ScrollView, TouchableOpacity} from 'react-native';

const ProductDetailScroll = () => {
  const scrollRef = useRef();
  return (
    <Fragment>
      <ParallaxScrollView
        backgroundColor="blue"
        contentBackgroundColor="pink"
        parallaxHeaderHeight={300}
        // renderScrollComponent={() => <Animated.View />}
        // renderScrollComponent={() =>  }
        renderForeground={() => (
          <View
            style={{
              height: 300,
              flex: 1,
              alignItems: 'center',
              justifyContent: 'center',
            }}>
            <Text>Hello World!</Text>
          </View>
        )}>
        <ScrollView style={{height: 500}} ref={scrollRef}>
          <View>
            <Text>
              Your project contains lock files generated by tools other than
              Yarn. It is advised not to mix package managers in order to avoi d
              resolution inconsistencies caused by unsynchronized lock files. To
              clear this warning, remove pack
            </Text>
          </View>
        </ScrollView>
      </ParallaxScrollView>
      <TouchableOpacity
        onPress={() => {
          scrollRef.current.scrollTo({x: 0, y: 0, animated: true});
        }}>
        <Text> scroll top </Text>
      </TouchableOpacity>
    </Fragment>
  );
};
export default ProductDetailScroll;
